# roles/database/tasks/main.yml
---
- name: 1.mysql server installation 
  become: yes
  become_user: root
  apt: name=mysql-server state=present

- name: 2. python-Mysql installation for mysql tasks  
  become: yes
  become_user: root
  apt: name=python-mysqldb state=present

- name: 3. Starting Mysql Service
  become: yes
  become_user: root
  service: name=mysql state=started enabled=true

- name: 4. removing test db
  become: yes
  become_user: root
  mysql_db: name=test state=absent

- name: 5. user creation for mysql
  become: yes
  become_user: root
  mysql_user: user="root" host="127.0.0.1" password=¨"wadoud1" priv=*.*:ALL,GRANT state=present

- name: 6. database creation
  become: yes
  become_user: root
  mysql_db: name=devops_projet state=present collation=utf8_general_ci

- name: 7. Updating mysql root password for all root accounts
  become: yes
  become_user: root
  mysql_user: name=root host={{item}} password="wadoud1"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost


- name: 7. Copying db data
  become: yes
  become_user: root
  copy: src=devops_projet.sql dest=/tmp/devops_projet.sql
  
- name: 8. Inserting db data
  become: yes
  become_user: root
  shell: cat /tmp/devops_projet.sql | sudo mysql -uroot -pwadoud1 devops_projet

- name: 9. Installing MySQL extension for PHP
  become: yes
  become_user: root
  apt: name=php-mysql state=present

- name: 10. Restarting Apache
  become: yes
  become_user: root
  service: name=apache2 state=restarted

- name: 11. copying php-mysql connexion script 
  become: yes
  become_user: root  
  copy: src=connex.php dest=/var/www/html/connex.php mode=777
