# roles/database/tasks/main.yml
---
- name: 1. Install mysql server package
  become: yes
  become_user: root
  apt: name=mysql-server state=present

- name: 1.2 Install python Mysql package #required for mysql_db tasks
  become: yes
  become_user: root
  apt: name=python-mysqldb state=present

- name: 2. Start Mysql Service
  become: yes
  become_user: root
  service: name=mysql state=started enabled=true

- name: 3. remove test db
  become: yes
  become_user: root
  mysql_db: name=test state=absent

- name: 4. Create user for mysql
  become: yes
  become_user: root
  mysql_user: user="wadoud" host="localhost" password=¨"wadoud1" priv=*.*:ALL,GRANT state=present



- name: Copy .my.cnf file with root password credentials
  become: yes
  become_user: root
  template: src=templates/.my.cnf dest=/etc/mysql/my.cnf owner=root mode=0600

- name: Update mysql root password for all root accounts
  become: yes
  become_user: root
  mysql_user: name=root host={{item}} password="wadoud1"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost


- name: 5a. Copy sample data
  become: yes
  become_user: root
  copy: src=dump.sql dest=/tmp/dump.sql
  
- name: 5b. Insert sample data
  become: yes
  become_user: root
  shell: cat /tmp/dump.sql | sudo mysql -uwadoud -pwadoud1 devops_projet

- name: 6a. Install MySQL extension for PHP
  become: yes
  become_user: root
  apt: name=php-mysql state=present

- name: 6b. Restart Apache
  become: yes
  become_user: root
  service: name=apache2 state=restarted

- name: 7. copying php script 
  become: yes
  become_user: root  
  copy: src=db.php dest=/var/www/html/db.php mode=0664
